// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJs-whBMyy5kElat47ec0-NCtC-OfjU8o',
    appId: '1:7957823585:web:b60ca84eeea993e9b8ea20',
    messagingSenderId: '7957823585',
    projectId: 'fluttermusicapp-4c1cb',
    authDomain: 'fluttermusicapp-4c1cb.firebaseapp.com',
    storageBucket: 'fluttermusicapp-4c1cb.appspot.com',
    measurementId: 'G-YV64RLH6CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1IYRa7hFX8qsc-QQubi0QGERcfJGMuJY',
    appId: '1:7957823585:android:a7abda89c0d7ebe1b8ea20',
    messagingSenderId: '7957823585',
    projectId: 'fluttermusicapp-4c1cb',
    storageBucket: 'fluttermusicapp-4c1cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRxGg15FaT-nZDc_i-W9Kf5wfIaNqDwvA',
    appId: '1:7957823585:ios:03dd729fac077748b8ea20',
    messagingSenderId: '7957823585',
    projectId: 'fluttermusicapp-4c1cb',
    storageBucket: 'fluttermusicapp-4c1cb.appspot.com',
    iosBundleId: 'com.example.musicApp',
  );
}
